version: "2"

run:
  timeout: 10m
  go: "1.25"

linters:
  default: none
  enable:
    - govet         # Vet examines Go source code
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Static analysis
    - unused        # Check for unused constants, variables, functions
    - misspell      # Spell checker
    - unconvert     # Remove unnecessary type conversions
    - unparam       # Report unused function parameters
    - goprintffuncname  # Check printf-like functions
